# Generated by Django 6.0.1 on 2026-01-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'Архив')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'Архив')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Формат обучения',
                'verbose_name_plural': 'Форматы обучения',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('lead', models.TextField(verbose_name='Лид')),
                ('about_description', models.TextField(verbose_name='Описание "О программе"')),
                ('curriculum', models.TextField(verbose_name='Программа обучения (учебный план)')),
                ('target_audience', models.TextField(verbose_name='Целевая аудитория')),
                ('enrollment_process', models.TextField(blank=True, verbose_name='Порядок зачисления')),
                ('hours_volume', models.PositiveIntegerField(verbose_name='Объём программы в часах')),
                ('duration', models.CharField(max_length=255, verbose_name='Календарная длительность')),
                ('cost', models.CharField(max_length=255, verbose_name='Стоимость')),
                ('outcome', models.TextField(blank=True, verbose_name='Итог по программе')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к слушателям')),
                ('learning_outcomes', models.TextField(blank=True, verbose_name='Результаты обучения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.direction', verbose_name='Направление')),
                ('learning_formats', models.ManyToManyField(related_name='programs', to='core.learningformat', verbose_name='Форматы обучения')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название/номер потока')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('schedule', models.TextField(blank=True, verbose_name='Расписание')),
                ('seats_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('status', models.CharField(choices=[('enrollment_open', 'Набор открыт'), ('enrollment_closed', 'Набор закрыт'), ('in_progress', 'Идет обучение'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='enrollment_open', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('learning_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.learningformat', verbose_name='Формат проведения')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Поток/Набор',
                'verbose_name_plural': 'Потоки/Наборы',
                'ordering': ['-start_date'],
            },
        ),
    ]
