# Generated by Django 6.0.1 on 2026-02-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_change_learning_formats_to_learning_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningformat',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Форма обучения', 'verbose_name_plural': 'Формы обучения'},
        ),
        migrations.AlterField(
            model_name='coursebatch',
            name='learning_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.learningformat', verbose_name='Форма проведения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='about_description',
            field=models.TextField(help_text='Подробное описание программы ("О программе")', verbose_name='Описание "О программе"'),
        ),
        migrations.AlterField(
            model_name='program',
            name='cost',
            field=models.CharField(help_text='Стоимость программы (например: "10000 руб", "Бесплатно")', max_length=255, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи программы', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='program',
            name='curriculum',
            field=models.TextField(help_text='Программа обучения (учебный план)', verbose_name='Программа обучения (учебный план)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='direction',
            field=models.ForeignKey(help_text='ID направления (категории) программы', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(help_text='Календарная длительность программы (например: "2 месяца", "72 часа")', max_length=255, verbose_name='Календарная длительность'),
        ),
        migrations.AlterField(
            model_name='program',
            name='enrollment_process',
            field=models.TextField(blank=True, help_text='Порядок зачисления на программу', verbose_name='Порядок зачисления'),
        ),
        migrations.AlterField(
            model_name='program',
            name='hours_volume',
            field=models.PositiveIntegerField(help_text='Объём программы в академических часах', verbose_name='Объём программы в часах'),
        ),
        migrations.AlterField(
            model_name='program',
            name='lead',
            field=models.TextField(help_text='Краткое описание программы (лид)', verbose_name='Лид'),
        ),
        migrations.AlterField(
            model_name='program',
            name='learning_format',
            field=models.ForeignKey(blank=True, help_text='Форма обучения (например: "Очная", "Онлайн")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.learningformat', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Результаты обучения (компетенции, которые приобретает слушатель)', verbose_name='Результаты обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Название программы повышения квалификации', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='program',
            name='outcome',
            field=models.TextField(blank=True, help_text='Итог по программе (что получает слушатель после завершения)', verbose_name='Итог по программе'),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirements',
            field=models.TextField(blank=True, help_text='Требования к слушателям для зачисления на программу', verbose_name='Требования к слушателям'),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('archived', 'Архив')], default='draft', help_text='Статус программы: "draft" (черновик), "active" (активен), "archived" (архив)', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='program',
            name='target_audience',
            field=models.TextField(help_text='Описание целевой аудитории программы', verbose_name='Целевая аудитория'),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи программы', verbose_name='Дата обновления'),
        ),
    ]
