# Generated by Django 6.0.1 on 2026-09-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_crm_appeals_and_staff_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('value', models.TextField(verbose_name='Значение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='corporaterequest',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='coursebatch',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='direction',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='learningformat',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursebatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learningformat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
