# Generated by Django 5.0.8 on 2026-03-04 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('category_type', models.CharField(blank=True, help_text='Для новостей/публикаций или общий', max_length=50, verbose_name='Тип категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'Новость'), ('article', 'Статья'), ('case', 'Кейс'), ('testimonial', 'Отзыв')], db_index=True, max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_moderation', 'На модерации'), ('published', 'Опубликовано'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='publications/%Y/%m/', verbose_name='Основное изображение')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='На главной')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('client_company', models.CharField(blank=True, max_length=255, verbose_name='Компания клиента')),
                ('client_industry', models.CharField(blank=True, max_length=255, verbose_name='Отрасль')),
                ('services', models.TextField(blank=True, verbose_name='Услуги/курсы')),
                ('results_short', models.TextField(blank=True, verbose_name='Краткий результат')),
                ('results_detailed', models.TextField(blank=True, verbose_name='Подробные результаты')),
                ('metrics', models.TextField(blank=True, verbose_name='Метрики')),
                ('person_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('person_position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('quote', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='publications/%Y/%m/', verbose_name='Логотип компании')),
                ('categories', models.ManyToManyField(blank=True, related_name='publications', to='publications.category', verbose_name='Категории')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publications', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_publications', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('tags', models.ManyToManyField(blank=True, related_name='publications', to='publications.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-published_at', 'sort_order'],
            },
        ),
    ]
