# Generated by Django 5.0.8 on 2026-03-04 07:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='client_company',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='client_industry',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='person_position',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='results_detailed',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='results_short',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='services',
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('article', 'Статья')], db_index=True, help_text='Тип публикации: новость или статья.', max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('client_company', models.CharField(max_length=255, verbose_name='Компания клиента')),
                ('client_industry', models.CharField(blank=True, max_length=255, verbose_name='Отрасль')),
                ('services', models.TextField(blank=True, verbose_name='Услуги/курсы')),
                ('results_short', models.TextField(blank=True, verbose_name='Краткий результат')),
                ('results_detailed', models.TextField(blank=True, verbose_name='Подробные результаты')),
                ('metrics', models.TextField(blank=True, verbose_name='Метрики')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='publications/cases/%Y/%m/', verbose_name='Основное изображение')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_moderation', 'На модерации'), ('published', 'Опубликовано'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='На главной')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('categories', models.ManyToManyField(blank=True, related_name='cases', to='publications.category', verbose_name='Категории')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('tags', models.ManyToManyField(blank=True, related_name='cases', to='publications.tag', verbose_name='Теги')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cases', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-published_at', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('person_position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('quote', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='publications/testimonials/%Y/%m/', verbose_name='Логотип компании')),
                ('slug', models.SlugField(help_text='Slug отзыва для публичного API.', max_length=500, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_moderation', 'На модерации'), ('published', 'Опубликовано'), ('archived', 'Архив')], db_index=True, default='on_moderation', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='На главной')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
