# Generated by Django 6.0.1 on 2026-09-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_publication_client_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовые данные'),
        ),
    ]
